# -*- coding: utf-8 -*-

VDISK_STATUS_AVAILABLE = "available"
VDISK_STATUS_ERROR = "error"
VDISK_STATUS_INUSE = "in-use"
VDISK_STATUS_CREATE = "creating"
VDISK_STATUS_ATTACH = "attaching"
VDISK_STATUS_BACKUP = "backuping"
VDISK_STATUS_DELETE = "deleting"
VDISK_STATUS_RECOVER = "recovering"

TYPE_VDISK = 0
TYPE_SYS_VOLUME = 1
TYPE_SNAPSHOT_VOLUME = 2
TYPE_SYS_IMAGE_VOLUME = 3
TYPE_BACKUP_RECOVER_VOLUME=4
TYPE_NEED_DELETE_VOLUME=5

VOLUME_SEQUENCE_NAME = "volume-sequence"
VOLUME_SEQUENCE_MAX = 9999
VOLUME_SEQUENCE_PREFIX = "vd-"
