# -*- coding: utf-8 -*-

__author__ = 'litao@easted.com.cn'
STATE_INTERVAL_TIME = 3
VM_DETAIL_PIE_INTERVAL_TIME = 5
VM_DETAIL_CHART_INTERVAL_TIME = 5
VM_DETAIL_ALARM_INTERVAL_TIME = 3
DASHBOARD_TOP_INTERVAL_TIME = 10
DASHBOARD_STAT_INTERVAL_TIME = 10
DASHBOARD_ALARM_INTERVAL_TIME = 10
DASHBOARD_LOG_INTERVAL_TIME = 10
HOST_DETAIL_CHART_INTERVAL_TIME = 5
HOST_DETAIL_VMS_INTERVAL_TIME = 5
HOST_DETAIL_ALARM_INTERVAL_TIME = 3
VM_DETAIL_LOG_INTERVAL_TIME = 5
SNAPSHOT_LOG_INTERVAL_TIME = 5
