# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-06 11:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrowserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('useragent', models.CharField(default='', max_length=100, verbose_name='\u7528\u6237\u6d4f\u89c8\u5668Agent\u4fe1\u606f')),
            ],
            options={
                'db_table': 'browserinfo',
                'verbose_name': '\u7528\u6237\u8bbf\u95eel\u6d4f\u89c8\u5668\u4fe1\u606f',
                'verbose_name_plural': '\u7528\u6237\u8bbf\u95eel\u6d4f\u89c8\u5668\u4fe1\u606f',
            },
        ),
        migrations.CreateModel(
            name='UserIPInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(default='', max_length=40, verbose_name='\u8282\u70b9IP\u5730\u5740')),
                ('time', models.DateField(auto_now=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
            ],
            options={
                'db_table': 'useripinfo',
                'verbose_name': '\u7528\u6237\u8bbf\u95ee\u5730\u5740\u4fe1\u606f',
                'verbose_name_plural': '\u7528\u6237\u8bbf\u95ee\u5730\u5740\u4fe1\u606f',
            },
        ),
        migrations.AddField(
            model_name='browserinfo',
            name='user_ip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scanhosts.UserIPInfo'),
        ),
    ]
