#!/usr/bin/env bash

value=0
while [[ $value != 1 ]]
do
	ping -c 2 ${Management_node}  1>/dev/null 2>&1
	if [ $? -eq 0 ]
	then
		sleep 30		
		value=1
		
		scp ${Management_node}:/etc/hosts /etc/hosts
		ntpdate -u ${Management_node}
		chown -R root:kvm /dev/kvm
		chmod -R 666 /dev/kvm
	else
		value=0
	fi
	sleep 10
done
