#!/usr/bin/env bash

printf "\033[1;4;47;32mPlease input the compute node hostname of you will remove:\033[0m"
read RA_HOST

if [ ! -f /root/keystonerc_admin ]
then 
	echo -e "\033[41;37mCan not find keystonerc_admin file in \"/root\", please check! \033[0m"
	exit 0
fi

source /root/keystonerc_admin
check_result=`nova service-list | grep -w nova-compute | grep -w ${RA_HOST}`
if [ -z "${check_result}" ]
then
	echo -e "\033[41;37mCan not find the host of \"${RA_HOST}\", please check! \033[0m"
	exit 0
fi

printf "\033[1;4;47;32mPlease input the DataBase node IP address:\033[0m"
read DB_IP
ping -c 2 ${DB_IP} >/dev/null
if [ $? -eq 0  ]
then
	printf ""
else
	printf "\033[41;37mConnect DataBase node faild, please check! \033[0m \n"
	exit 0
fi

printf "\033[1;4;47;32mPlease input the database root user access password:\033[0m"
DB_PASSWD=
while : ;do
	char=`
		stty cbreak -echo
		dd if=/dev/tty bs=1 count=1 2>/dev/null
		stty -cbreak echo
	`
	if [ "$char" =  "" ];then
		break
	fi
	DB_PASSWD="$DB_PASSWD$char"
	echo -n "*"
done
echo

ssh ${DB_IP} "mysql -uroot -p${DB_PASSWD} -e \"quit\""
if [[ $? -eq 0 ]]
then
	printf ""
else
	echo -e "\033[1;4;31mAccess DataBase Faild! \033[0m"
	exit 0
fi


mysql -h${DB_IP} -uroot -p${DB_PASSWD} -e "delete from nova.services where host = '${RA_HOST}' and topic = 'compute';"
mysql -h${DB_IP} -uroot -p${DB_PASSWD} -e "delete from nova.compute_nodes where host = '${RA_HOST}';"
echo -e "\033[32mRemove the host of \"${RA_HOST}\" nova service\033[0m"
mysql -h${DB_IP} -uroot -p${DB_PASSWD} -e "delete from neutron.agents where host = '${RA_HOST}' and agent_type = 'Open vSwitch agent';"
echo -e "\033[32mRemove the host of \"${RA_HOST}\" neutron service\033[0m"
mysql -h${DB_IP} -uroot -p${DB_PASSWD} -e "delete from cinder.services where availability_zone = '${RA_HOST}';"
echo -e "\033[32mRemove the host of \"${RA_HOST}\" cinder service\033[0m"

openstack-service restart nova
openstack-service restart neutron
openstack-service restart cinder 
echo -e "\033[32mRemove compute node \"${RA_HOST}\" successful\033[0m"